name: panseg-dev
channels:
  - conda-forge
dependencies:
  - bioimageio.core==0.10.2
  - bioimageio.spec==0.5.9.1
  - bump-my-version
  - h5py==3.16.0
  - mike
  - mkdocs-autorefs
  - mkdocs-git-committers-plugin-2
  - mkdocs-git-revision-date-localized-plugin
  - mkdocs-material
  - mkdocstrings-python
  - napari==0.7.0
  - numpy==2.4.3
  - pip
  - pre-commit
  - pydantic==2.13.3
  - pyside6==6.11.0
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-qt
  - python-elf==0.7.4
  - python-graphviz==0.21
  - python=3.11
  - pytorch==2.10.0
  - pyyaml==6.0.3
  - qt-material==2.14
  - qtpy==2.4.3
  - requests-mock
  - requests==2.33.1
  - scikit-image==0.26.0
  - tensorboard==2.20.0
  - tifffile==2026.3.3
  - trimesh==4.11.5
  - zmesh==1.11.0
  - vigra==1.12.3
  - zarr==3.1.6
  - pip:
      - markdown-exec
      - -e .
