{% set PYTHON_MIN = "3.11" %}
package:
  name: panseg
  version: "2.0.0"

source:
  path: ..

build:
  noarch: python
  number: 2
  script:
    - "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-cache-dir"
    - "mkdir -p {{ PREFIX }}/Menu" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/panseg.json {{ PREFIX }}/Menu/{{ PKG_NAME }}_menu.json" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/icon.png {{ PREFIX }}/Menu/icon.png" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/icon.ico {{ PREFIX }}/Menu/icon.ico" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/logo_horizontal.png {{ PREFIX }}/Menu/logo_horizontal.png" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/logo_vertical.png {{ PREFIX }}/Menu/logo_vertical.png" # [not win]

  entry_points:
    - panseg = panseg.run_panseg:main

requirements:
  build:
    - python {{ PYTHON_MIN }}
    - pip
    - setuptools

  run:
    - python >={{ PYTHON_MIN }}
    - pip
    - bioimageio.core ==0.10.0
    - bioimageio.spec ==0.5.9.0
    - h5py ==3.16.0
    - napari ==0.7.0
    - pydantic ==2.12.5
    - pyside6 ==6.11.0
    - python-elf ==0.7.4
    - python-graphviz ==0.21
    - pytorch ==2.10.0
    - pyyaml ==6.0.3
    - qt-material ==2.14
    - qtpy ==2.4.3
    - requests ==2.33.1
    - scikit-image ==0.26.0
    - tensorboard ==2.20.0
    - tifffile ==2026.3.3
    - vigra ==1.12.2
    - trimesh ==4.11.5
    - numpy ==2.4.3
    - zarr ==3.1.5
    - zmesh ==1.11.0

test:
  requires:
    - python {{ PYTHON_MIN }}
  imports:
    - panseg

about:
  home: https://kreshuklab.github.io/panseg/
  license: MIT
