import json
import logging
import sys
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from functools import wraps
from inspect import signature
from pathlib import Path
from typing import Any, Callable, Literal
from uuid import UUID, uuid4

import yaml
from pydantic import BaseModel, Field, field_validator
from rich.traceback import Traceback

from panseg.__version__ import __version__
from panseg.core.image import PanSegImage, restack_timepoints

logger = logging.getLogger(__name__)


class NodeType(str, Enum):
    NODE = "node"
    ROOT = "root"
    LEAF = "leaf"


class RunTimeInputSchema(BaseModel):
    description: str | None = None
    task: str | None = None
    required: bool = True
    default: Any = None
    is_input_file: bool = False


@dataclass
class Task_message:
    message: str
    name: str
    level: Literal["warning", "info", "debug"] = "warning"

    def __post_init__(self):
        exc_type, exc_value, exc_traceback = sys.exc_info()
        self.trace = Traceback.from_exception(
            exc_type, exc_value, exc_traceback, show_locals=True
        )


class Infos(BaseModel):
    """
    Information about the workflow.

    Attributes:
        description (str): An optional description of the workflow. This is only used for documentation purposes.
        creation_date (str): The date and time when the workflow was created. This is automatically generated.
        version (str): The version of panseg used to create the workflow.
        inputs_schema (dict[str, RunTimeInputSchema]): A dictionary with the schema of the inputs of the workflow.
        instructions (str): Instructions on how to customize the workflow file.
    """

    description: str = "No description provided"
    creation_date: str = Field(
        default_factory=lambda: datetime.now().strftime("%Y-%m-%d-%H:%M:%S")
    )
    version: str = __version__
    inputs_schema: dict[str, RunTimeInputSchema] = Field(default_factory=dict)
    instructions: str = (
        "This configuration file was generated by PanSeg and can be used to run a headless workflow. "
        "In order to run the workflow, you will need to customize this file with the correct paths and parameters. "
        "To read detailed instructions on how to do this, please visit the PanSeg documentation (https://kreshuklab.github.io/panseg/)."
    )


class Task(BaseModel):
    func: str
    images_inputs: dict
    parameters: dict
    outputs: list[str]
    node_type: NodeType
    id: UUID = Field(default_factory=uuid4)
    skip: bool = False

    """
    A task is a single operation in the workflow. It is defined by:

    Attributes:
        func (str): The name of the function to be executed
        images_inputs (dict): A image input represent a Image object.
            The key is the name of the parameter in the function, and the value is the name of the image.
        parameters (dict): The kwargs parameters of the workflow function.
        outputs (list[str]): A list of the names of the output images.
        node_type (NodeType): The type of the node in the workflow (ROOT, LEAF, NODE)
        id (UUID): A unique identifier for the task.
        skip (bool): If True, the task will be skipped during the execution of the workflow.
            This is useful to remove a task that requires manual intervention (like a cropping task from the GUI).

    """


class DAG(BaseModel):
    infos: Infos = Field(default_factory=Infos)
    inputs: dict[str, Any] = Field(default_factory=dict)
    list_tasks: list[Task] = Field(default_factory=list)

    """
    This model represents the Directed Acyclic Graph (DAG) of the workflow.

    Attributes:
        infos (Infos): A dictionary with the information of the workflow.
        inputs (dict[str, Any]): A dictionary of the inputs of the workflow. For example path to the images and other runtime parameters.
        list_tasks (list[Task]): A list of the tasks in the workflow.

    """

    @field_validator("inputs", mode="before")
    @classmethod
    def _coerce_legacy_inputs(cls, value):
        # Workflow files saved before the inputs field was a plain dict
        # stored the inputs as a list with a single dict entry.
        if isinstance(value, list):
            if len(value) == 0:
                return {}
            if len(value) == 1 and isinstance(value[0], dict):
                return value[0]
            raise ValueError(
                "A DAG holds the inputs of a single workflow, but a list of "
                f"{len(value)} input dicts was given. Such a list is a headless "
                "batch configuration: run it with `panseg --config` / "
                "run_headless_workflow instead of loading it as a DAG."
            )
        return value

    @property
    def list_inputs(self):
        return list(self.infos.inputs_schema.keys())


def prune_dag(dag: DAG) -> DAG:
    """
    Remove all the tasks that are not connected to the leaf nodes.
    """

    # Initialize the reachable set with the leaf nodes
    reachable = set()
    reachable_inputs = set()
    for task in dag.list_tasks:
        if task.node_type == NodeType.LEAF:
            for inp_key in task.images_inputs.values():
                reachable.add(task.id)
                reachable_inputs.add(inp_key)

    safety_counter = 0
    size_reachable = len(reachable)
    while True:
        # For each task check if the outputs is connected to the reachable set
        # if so, add the task to the reachable set
        for task in dag.list_tasks:
            for out_key in task.outputs:
                if out_key in reachable_inputs:
                    reachable.add(task.id)
                    for inp_key in task.images_inputs.values():
                        reachable_inputs.add(inp_key)

        safety_counter += 1
        if safety_counter > 1_000_000:
            raise ValueError("Infinite loop in the pruning of the DAG")

        # If the size of the reachable set did not change, we are done pruning
        if size_reachable == len(reachable):
            break
        size_reachable = len(reachable)

    new_dag = DAG()
    for task in dag.list_tasks:
        if task.id in reachable:
            new_dag.list_tasks.append(task)

    for input_key, text in dag.inputs.items():
        if input_key in reachable_inputs:
            new_dag.inputs[input_key] = text
            new_dag.infos.inputs_schema[input_key] = dag.infos.inputs_schema[input_key]

    return new_dag


class SingletonMeta(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            instance = super().__call__(*args, **kwargs)
            cls._instances[cls] = instance
        return cls._instances[cls]


class FuncsHandler(metaclass=SingletonMeta):
    """
    A singleton class to store the functions of the workflow.
    """

    def __init__(self):
        self._funcs = {}

    def register_func(self, func):
        self._funcs[func.__name__] = func

    def get_func(self, name):
        return self._funcs[name]

    def list_funcs(self):
        return list(self._funcs.keys())


class WorkflowHandler:
    """
    Container for a workflow. It stores the functions, the a list of tasks.
    """

    def __init__(self):
        self._funcs = FuncsHandler()
        self._dag = DAG()

    @property
    def dag(self) -> DAG:
        return self._dag

    @property
    def func_registry(self) -> FuncsHandler:
        return self._funcs

    def register_func(self, func):
        """
        Add a function to the workflow functions registry.
        """
        self._funcs.register_func(func)

    def add_task(
        self,
        func: Callable,
        images_inputs: dict,
        parameters: dict,
        outputs: list[str],
        node_type: NodeType,
    ):
        """
        Add a task to the workflow. This method is used by the task_tracker decorator and should not be called directly.

        Args:
            func (Callable): The function to be executed.
            images_inputs (dict): A dictionary of the image inputs. The key is the name of the parameter in the function,
                and the value is the unique_name of the image.
            parameters (dict): The kwargs parameters of the workflow function.
            outputs (list[str]): A list of the names of the output images.
            node_type (NodeType): The type of the node in the workflow (ROOT, LEAF, NODE)

        """
        assert func.__name__ in self._funcs.list_funcs(), (
            f"Function {func.__name__} not registered"
        )

        task = Task(
            func=func.__name__,
            images_inputs=images_inputs,
            parameters=parameters,
            outputs=outputs,
            node_type=node_type,
        )
        self._dag.list_tasks.append(task)

    def add_input(
        self,
        name: str,
        value: Any,
        value_schema: RunTimeInputSchema,
        func_name: str | None = None,
    ):
        def _unique_input(name, id: int = 0):
            new_name = f"{name}_{id}"
            if new_name not in self._dag.list_inputs:
                return new_name

            return _unique_input(name, id + 1)

        if name not in self._dag.list_inputs:
            unique_name = name
        else:
            unique_name = _unique_input(name)

        value_schema.task = func_name
        self._dag.infos.inputs_schema[unique_name] = value_schema

        self._dag.inputs[unique_name] = value
        return unique_name

    def clean_dag(self):
        self._dag = DAG()

    def prune_dag(self) -> DAG:
        """
        Remove all the tasks that are not connected to the leaf nodes.
        """
        return prune_dag(self._dag)

    def save_to_yaml(self, path: Path | str):
        clean_dag = self.prune_dag()
        dag_dict = json.loads(clean_dag.model_dump_json(exclude_none=True))

        if isinstance(path, str):
            path = Path(path)

        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, "w") as f:
            yaml.dump(dag_dict, f)

    def from_yaml(self, path: Path) -> "WorkflowHandler":
        """Load a workflow from a yaml file.

        The file must describe a single workflow: ``inputs`` is a dict (or a
        legacy list with a single dict entry). Headless batch configurations,
        where ``inputs`` is a list of one dict per job, are not workflows and
        are rejected; run them with `run_headless_workflow`.
        """
        with open(path, "r") as f:
            dag_dict = yaml.load(f, Loader=yaml.FullLoader)

        self._dag = DAG(**dag_dict)
        return self


workflow_handler = WorkflowHandler()


def _reject_timeseries_inputs(kwargs: dict, func_name: str) -> None:
    """Reject timeseries inputs to a task without explicit timeseries support."""
    for name, arg in kwargs.items():
        if isinstance(arg, PanSegImage) and arg.is_timeseries:
            raise ValueError(
                f"Task {func_name} received the timeseries image {name!r} but is "
                "neither frame-mapped (@timepoint_map) nor stack-level "
                "(task_tracker(stack_level=True)); timeseries support must be "
                "explicit per task."
            )


def _timeseries_guard(func: Callable) -> Callable:
    """Wrap a task so the registered callable rejects timeseries inputs too.

    The task_tracker wrapper guards the GUI path; the headless SerialRunner
    calls the registered callable, which is this guard.
    """

    @wraps(func)
    def guard(*args, **kwargs):
        _reject_timeseries_inputs(kwargs, func.__name__)
        return func(*args, **kwargs)

    return guard


def task_tracker(
    func: Callable | None = None,
    *,
    is_root=False,
    is_leaf=False,
    list_inputs: dict[str, RunTimeInputSchema] | None = None,
    stack_level: bool = False,
):
    """
    Decorator to register a function as a task in the workflow.
    To not set a parameter in headless mode its name must start with _

    Every task is explicitly frame-mapped or stack-level: a task that is
    neither rejects timeseries inputs on both execution paths.

    Args:
        func (Callable): The function that will be registered as a task.
        is_root (bool): If True, the function is a root node in the workflow
            (usually a import task).
        is_leaf (bool): If True, the function is a leaf node in the workflow
            (usually a writer task).
        list_inputs (dict[str, TaskUserInput]): A dictionary of the inputs of
            the function. The key is the name of the parameter
        stack_level (bool): If True, the task is classified stack-level: it
            operates on the whole timeseries as one object and accepts
            timeseries images (e.g. export_image_task). Defaults to False.
    """

    if is_root and is_leaf:
        raise ValueError("A node cannot be both root and leaf at the same time")

    if is_root:
        node_type = NodeType.ROOT
    elif is_leaf:
        node_type = NodeType.LEAF
    else:
        node_type = NodeType.NODE

    list_inputs = list_inputs or {}

    def _inner_decorator(func):
        frame_mapped = getattr(func, "__timepoint_mapped__", False)
        if frame_mapped or stack_level:
            workflow_handler.register_func(func)
        else:
            # the guard makes the headless path reject timeseries inputs too
            workflow_handler.register_func(_timeseries_guard(func))

        @wraps(func)
        def wrapper(*args, **kwargs):
            assert len(args) == 0, (
                "Workflow functions should not have positional arguments"
            )
            if not frame_mapped and not stack_level:
                _reject_timeseries_inputs(kwargs, func.__name__)
            func_signature = signature(func)
            parameters = {
                param: func_signature.parameters[param].default
                for param in func_signature.parameters
            }

            # Some tasks might have an arbitrary number of inputs (merge)
            # Those must be named kwargs
            parameters.pop("kwargs", None)

            images_inputs = {}

            for name, arg in kwargs.items():
                if isinstance(arg, PanSegImage):
                    images_inputs[name] = arg.unique_name
                    parameters.pop(name, None)

                elif name in list_inputs.keys():
                    value = list_inputs[name]
                    input_name = workflow_handler.add_input(
                        name, value=arg, value_schema=value, func_name=func.__name__
                    )
                    images_inputs[name] = input_name
                    parameters.pop(name)

                else:
                    # Replace the default value with the provided value
                    # _tracker for progressbars excluded
                    if name[0] != "_":
                        parameters[name] = arg

            # Execute the function
            try:
                out_image = func(*args, **kwargs)
            except Exception as e:
                out_image = Task_message(
                    message=str(e),
                    name=func.__name__,
                    level="warning",
                )

            # Parse the output
            if out_image is None:
                list_outputs = []

            elif isinstance(out_image, PanSegImage):
                list_outputs = [out_image.unique_name]

            elif isinstance(out_image, tuple) or isinstance(out_image, list):
                list_outputs = []
                for i, img in enumerate(out_image):
                    if not isinstance(img, PanSegImage):
                        raise ValueError(
                            f"Output {i} is not an Image object, but {type(img)}"
                        )
                    list_outputs.append(img.unique_name)

            elif isinstance(out_image, Task_message):
                # error message gets handled in schedulers callback `ondone`
                list_outputs = []
                return out_image

            else:
                raise ValueError(
                    f"Output of a workflow function should be one of None, Image or tuple of Images. Got {type(out_image)}"
                )

            for name in list_outputs:
                if name in images_inputs.values():
                    raise ValueError(
                        f"Function {func.__name__} has an output image with the same name as an input image: {name}"
                    )

            # Add the task to the workflow
            workflow_handler.add_task(
                func=func,
                images_inputs=images_inputs,
                parameters=parameters,
                outputs=list_outputs,
                node_type=node_type,
            )
            return out_image

        wrapper.__panseg_task__ = func.__name__
        return wrapper

    if func is None:
        return _inner_decorator

    return _inner_decorator(func)


def _timepoint_count(image: PanSegImage) -> int:
    """Number of timepoints of a timeseries image."""
    t_axis = image.time_axis
    assert t_axis is not None, "No time axis known!"
    return image.shape[t_axis]


def _restacked_name(output_name: str, timeseries_inputs: dict) -> str:
    """Strip the timepoint markers from a first-timepoint output name.

    Task bodies name their outputs from their input names (f"{name}_..."),
    and the input at timepoint 0 is named f"{parent.name}_t0": replacing
    each marker with the parent name yields the name the task gives a still
    image. Longer parent names are replaced first so a name that is a
    prefix of another cannot eat its marker.
    """
    name = output_name
    for parent_name in sorted(
        (image.name for image in timeseries_inputs.values()), key=len, reverse=True
    ):
        name = name.replace(f"{parent_name}_t0", parent_name)
    return name


def _restack_timepoint_outputs(
    results: list,
    timeseries_inputs: dict,
    task_name: str,
    shared_t_spacing: float | None,
):
    """Restack the per-timepoint outputs of a frame-mapped task.

    Every timepoint must return the same structure: one PanSegImage, a
    list/tuple of PanSegImages (restacked element-wise, e.g. both outputs
    of remove_false_positives_by_foreground_probability_task), or None.

    The restacked output takes the shared spacing of the timeseries
    inputs (the full rule is in the timepoint_map docstring): an output
    that carries no t_spacing - e.g. a body that rebuilt its image from
    scratch - falls back to the shared spacing with a warning, so a
    frame-mapped run never silently loses the input timing.
    """
    outputs_per_timepoint = []
    for result in results:
        if isinstance(result, PanSegImage):
            outputs_per_timepoint.append([result])
        elif isinstance(result, (list, tuple)):
            if not all(isinstance(image, PanSegImage) for image in result):
                raise ValueError(
                    "A frame-mapped task must return images, got "
                    + ", ".join(str(type(image)) for image in result)
                )
            outputs_per_timepoint.append(list(result))
        elif result is None:
            outputs_per_timepoint.append(None)
        else:
            raise ValueError(
                f"A frame-mapped task must return images, got {type(result)}"
            )

    if all(result is None for result in outputs_per_timepoint):
        return None
    if any(result is None for result in outputs_per_timepoint):
        raise ValueError("A frame-mapped task returned None only for some timepoints")

    n_outputs = {len(result) for result in outputs_per_timepoint}
    if len(n_outputs) > 1:
        raise ValueError(
            "A frame-mapped task returned a different number of outputs per timepoint: "
            f"{sorted(n_outputs)}"
        )
    n_outputs = n_outputs.pop()

    restacked = []
    for j in range(n_outputs):
        outputs = [result[j] for result in outputs_per_timepoint]
        t_spacing = outputs[0].properties.t_spacing
        if t_spacing is None and shared_t_spacing is not None:
            logger.warning(
                "Task %s: per-timepoint outputs carry no t_spacing, "
                "falling back to the inputs' shared t_spacing (%g s). "
                "Derive task outputs from their input (derive_new) or "
                "set t_spacing explicitly to avoid this.",
                task_name,
                shared_t_spacing,
            )
            t_spacing = shared_t_spacing
        restacked.append(
            restack_timepoints(
                outputs,
                # the task bodies left the effective spacing on their
                # outputs: preserved from the input, or overridden by a
                # property task like set_t_spacing_task
                t_spacing=t_spacing,
                t_unit=outputs[0].properties.t_unit,
                name=_restacked_name(outputs[0].name, timeseries_inputs),
            )
        )
    if n_outputs == 1:
        return restacked[0]
    return restacked


def timepoint_map(
    func: Callable | None = None,
    *,
    broadcast: bool = False,
):
    """
    Decorator that runs a task frame-by-frame over timeseries input.

    Use under @task_tracker. At call time the decorator inspects the keyword
    arguments: every PanSegImage input with is_timeseries is split into
    timepoints, the task body runs once per timepoint, and the outputs are
    restacked into a timeseries. A call without a timeseries input passes
    through untouched.

    The loop sits under the recording layer on both execution paths: the
    GUI runs the @task_tracker wrapper, the headless SerialRunner calls
    the registered callable, which is this wrapper.

    Rules:

    - All timeseries inputs must have the same number of timepoints and the
      same t_spacing (both unknown is fine); a mismatch raises ValueError.
    - The restacked output takes the inputs' shared t_spacing: a task body
      preserves it by deriving its outputs from the input (derive_new) or
      overrides it with a non-None t_spacing (e.g. set_t_spacing_task). A
      per-timepoint output that carries no t_spacing - e.g. a body that
      rebuilt its image from scratch instead of deriving it from the input
      - falls back to the shared spacing with a warning, so a frame-mapped
      run never silently loses the input timing.
    - A still image next to timeseries inputs raises ValueError unless the
      task opts in with broadcast=True: the still image is then applied to
      every timepoint (e.g. a static background).
    - The first failed timepoint aborts the run and its exception
      propagates; a Task_message returned by an inner call counts as a
      failure and propagates too.
    - A _tracker kwarg is driven at timepoint granularity (total = number
      of timepoints, one tick per completed timepoint); the per-timepoint
      calls see _tracker=None.
    - Timepoints are locals of the wrapper: they never enter var_space or
      the DAG node, which records the timeseries in and the restacked
      timeseries out with the same parameters as a still-image call.

    Args:
        func (Callable): The task function wrapped by this decorator.
        broadcast (bool): Opt in to applying still-image inputs to every
            timepoint instead of rejecting mixed inputs.
    """

    def _inner_decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            assert len(args) == 0, (
                "Workflow functions should not have positional arguments"
            )

            image_kwargs = {
                name: arg
                for name, arg in kwargs.items()
                if isinstance(arg, PanSegImage)
            }
            timeseries_inputs = {
                name: arg for name, arg in image_kwargs.items() if arg.is_timeseries
            }

            if not timeseries_inputs:
                return func(*args, **kwargs)

            t_lengths = {
                name: _timepoint_count(image)
                for name, image in timeseries_inputs.items()
            }
            if len(set(t_lengths.values())) > 1:
                raise ValueError(
                    f"Time series inputs to {func.__name__} have different numbers of "
                    "timepoints: "
                    + ", ".join(f"{name}={n}" for name, n in t_lengths.items())
                )
            n_timepoints = next(iter(t_lengths.values()))

            t_spacings = {
                name: image.properties.t_spacing
                for name, image in timeseries_inputs.items()
            }
            if len(set(t_spacings.values())) > 1:
                raise ValueError(
                    f"Time series inputs to {func.__name__} have different t_spacing "
                    "(seconds, None = unknown): "
                    + ", ".join(f"{name}={s}" for name, s in t_spacings.items())
                )
            shared_t_spacing = next(iter(t_spacings.values()))

            still_inputs = {
                name: arg for name, arg in image_kwargs.items() if not arg.is_timeseries
            }
            if still_inputs and not broadcast:
                raise ValueError(
                    f"Task {func.__name__} mixes timeseries and still image inputs: "
                    f"{sorted(still_inputs)}. It does not opt in to broadcasting a "
                    "still image to every timepoint."
                )

            # A timepoint loses t_spacing in the split; stamp the shared
            # spacing back on through the validated core API so task
            # bodies preserve it through derive_new and property tasks
            # can override it.
            timepoints_per_input = {
                name: image.split_timepoints()
                for name, image in timeseries_inputs.items()
            }
            for timepoints in timepoints_per_input.values():
                for timepoint in timepoints:
                    timepoint.set_t_spacing(shared_t_spacing)

            tracker = kwargs.get("_tracker")
            if tracker is not None:
                tracker.total = n_timepoints

            results = []
            for i in range(n_timepoints):
                call_kwargs = dict(kwargs)
                for name, timepoints in timepoints_per_input.items():
                    call_kwargs[name] = timepoints[i]
                if "_tracker" in call_kwargs:
                    call_kwargs["_tracker"] = None
                result = func(**call_kwargs)
                if isinstance(result, Task_message):
                    return result
                results.append(result)
                if tracker is not None:
                    tracker.progress += 1

            return _restack_timepoint_outputs(
                results, timeseries_inputs, func.__name__, shared_t_spacing
            )

        setattr(wrapper, "__timepoint_mapped__", True)
        return wrapper

    if func is None:
        return _inner_decorator

    return _inner_decorator(func)
