name: Release new version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
          - pre_label
          - pre_n

jobs:
  test-matrix:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ["${{ matrix.os }}"]

    defaults:
      run:
        shell: ${{ matrix.os == 'windows' && 'powershell' || 'bash -el {0}' }}

    steps:
      - name: Setup Qt headless display
        uses: pyvista/setup-headless-display-action@v3
        with:
          qt: true

      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Set Up Miniforge
        uses: conda-incubator/setup-miniconda@v4.0.0
        with:
          python-version: 3.11
          miniforge-version: latest
          mamba-version: "*"
          channels: local,conda-forge
          environment-file: "environment-dev.yaml"
          activate-environment: "panseg-dev"
          conda-remove-defaults: true

      - name: Run checks
        run: |
          pytest --cov --cov-report=xml --durations=10

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-and-build:
    needs: test-matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      DISPLAY: ":99.0"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Setup Qt headless display
        uses: pyvista/setup-headless-display-action@v3
        with:
          qt: true

      - name: Set Up Miniforge
        uses: conda-incubator/setup-miniconda@v4.0.0
        with:
          python-version: 3.11
          miniforge-version: latest
          mamba-version: "*"
          channels: conda-forge
          conda-remove-defaults: true

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@v1.3
        with:
          args: "--verbose ${{ inputs.bump-type }}"
          github-token: ${{ secrets.RELEASE_BUMP_MY_VERSION_PAT }}

      - name: Check version
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"

      - name: Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          generate_release_notes: true
          tag_name: ${{ steps.bump.outputs.current-version }}
          name: ${{ steps.bump.outputs.current-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
          prerelease: ${{ startsWith( inputs.bump-type , 'pre' ) }}

      - name: conda build
        run: |
          conda create -n builder conda-build
          conda activate builder
          conda build conda-recipe/ --output-folder conda_bld
          conda deactivate

      - name: tar build
        run: |
          tar czf ./constructor/build.gz conda_bld/*
          ls
          echo "### ls constructor: ###"
          ls ./constructor

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: panseg-conda-build
          path: constructor/build.gz
          overwrite: true
          if-no-files-found: error

      - name: Trigger building docs
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run build-and-publish-docs.yml -f version=${{ steps.bump.outputs.current-version }}

  build_installer:
    needs: test-and-build
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ["${{ matrix.os }}"]

    defaults:
      run:
        # Conda requires a login shell in order to work properly
        shell: ${{ matrix.os == 'windows' && 'powershell' || 'bash -el {0}' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Checkout new release
        run: |
          git fetch
          git checkout main
          git pull
          cat panseg/__version__.py

      - uses: actions/download-artifact@v8.0.1
        with:
          name: panseg-conda-build
          path: ./constructor

      - name: Display downloaded files
        run: ls ./constructor

      - name: Set Up Miniforge
        uses: conda-incubator/setup-miniconda@v4.0.0
        with:
          python-version: 3.12
          miniforge-version: latest
          mamba-version: "*"
          channels: conda-forge
          conda-remove-defaults: true
          activate-environment: "dummyenv"

      - name: List Conda Environments
        run: |
          conda info --envs

      - name: create package
        run: |
          conda create -n constructor constructor menuinst requests
          conda activate constructor
          constructor --output-dir installer constructor/
          conda deactivate

      - name: publish to heibox and release using python uploader
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda activate constructor
          python -u constructor/uploader.py ${{ secrets.SEAFILE_API_TOKEN }}
          conda deactivate

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: "panseg-installer-${{ matrix.os }}"
          path: installer/PanSeg*
          overwrite: true
          if-no-files-found: error
