name: Manually run tests on all platforms

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ["${{ matrix.os }}"]

    defaults:
      run:
        shell: ${{ matrix.os == 'windows' && 'powershell' || 'bash -el {0}' }}

    steps:
      - name: Setup Qt headless display
        uses: pyvista/setup-headless-display-action@v4.3
        with:
          qt: true

      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Set Up Miniforge
        uses: conda-incubator/setup-miniconda@v4.0.0
        with:
          python-version: 3.11
          miniforge-version: latest
          mamba-version: "*"
          channels: local,conda-forge
          environment-file: "environment-dev.yaml"
          activate-environment: "panseg-dev"
          conda-remove-defaults: true

      - name: Run checks
        run: |
          panseg --help
          pytest --cov --cov-report=xml --durations=10

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
